version: '2.3'

services:
  face_obfuscator:
    image: face_obfuscator
    container_name: face_obfuscator
    working_dir: /opt/face_obfuscator
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: python3 -u face_obfuscator.py
    volumes:
      - ./input:/input
      - ./output:/output
    runtime: nvidia
