version: '2.3'

services:
  face_obfuscator:
    image: face_obfuscator
    container_name: face_obfuscator
    working_dir: /opt/face_obfuscator
    build:
      context: .
      #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
      # dockerfile: Dockerfile.gpu 
    command: python3 face_obfuscator.py
    volumes:
      - ./:/workspace
    #Uncomment this line to run the example on the GPU (requires Nvidia-Docker)
    # runtime: nvidia
