version: '2.3'

services:
  face_obfuscator:
    image: face_obfuscator_gpu
    container_name: face_obfuscator_gpu
    working_dir: /opt/face_obfuscator
    build:
      context: .
      dockerfile: Dockerfile.gpu
    command: python3 -u face_obfuscator.py
    volumes:
      - ./input:/input
      - ./output:/output
    runtime: nvidia
    environment: 
      DOWNSCALE_FPS: ${DOWNSCALE_FPS}
      DOWNSCALE_RES: ${DOWNSCALE_RES}
